### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by sancelot** [testillano/json2xml#1]
```
/home/sancelot/git/aicon_automation_api/json2xml.hpp:135:17: error: ‘binary_t’ has not been declared  
     bool binary(binary_t& val) override  
                 ^~~~~~~~  
/home/sancelot/git/aicon_automation_api/json2xml.hpp:135:10: error: ‘bool ert::JsonSaxConsumer::binary(int&)’ marked  
 ‘override’, but does not override  
     bool binary(binary_t& val) override  
          ^~~~~~  
```

**Comment by testillano** [comment]
Which nlohmann json header are you using?
I think this error comes from using an old one. Try this: https://github.com/testillano/json2xml/blob/034e49aa14054d5ddc5611f88c6cec7262494d4b/CMakeLists.txt#L33
The binary method was added recently. Indeed is pending to be implemented here, but using the proper json header it will compile and you may ignore it if you dont use in your documents.
Let me know if works.
BRs
